site_name: Naija News Hub
site_description: Nigerian News Aggregation & Analysis Platform
site_author: Jeremiah Agenyi
site_url: https://jerryagenyi.github.io/naija-news-hub/

# GitHub Pages configuration
repo_name: jerryagenyi/naija-news-hub
repo_url: https://github.com/jerryagenyi/naija-news-hub
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Project Overview:
    - Original Concept: docs/original-idea.md
    - Product Requirements: docs/prd.md
  - Development:
    - Documentation Guide: docs/documentation-guide.md
    - Project Management: docs/pm/
    - Development Guide: docs/dev/
  - App Documentation: docs/app/
  - User Guide: docs/guide/

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true 